:queues:
  - priority
  - default
:schedule:
  update_wallet_assets_job:
    every: "1s"
    class: UpdateWalletAssetsJob
  update_not_wallet_assets_job:
    every: "1s"
    class: UpdateNotWalletAssetsJob
